#!/bin/bash

echo "🚀 Pushing database schema to Railway..."
echo ""
echo "This will sync your local schema with Railway's database."
echo "Make sure you have Railway CLI installed and are logged in."
echo ""
echo "Run these commands:"
echo ""
echo "1. Push schema changes to Railway database:"
echo "   railway run npm run db:push"
echo ""
echo "2. Or if you have direct database access, run migrations:"
echo "   railway run npx drizzle-kit push:pg"
echo ""
echo "3. After schema is updated, create test users:"
echo "   railway run node scripts/create-test-users.js"
echo ""
echo "The issue is that Railway's database is missing the 'is_epic' column"
echo "and possibly other columns that were added to the schema later."